DROP DATABASE IF EXISTS searchapp:

CREATE DATABASE searchapp CHARACTER SET utf8;

USE searchapp;

CREATE TABLE topic (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NULL DEFAULT NULL,
    description VARCHAR(5000) NULL DEFAULT NULL,
    text_field1 VARCHAR(5000) NULL DEFAULT NULL,
    text_field2 VARCHAR(5000) NULL DEFAULT NULL,
    created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
)
ENGINE=InnoDB;